# 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code modules that you can use to perform common tasks, saving you time and effort.

# 2. What is the difference between Numpy array and List?

NumPy Array: Provides a wide range of mathematical functions and supports multi-dimensional arrays, making it suitable for numerical and scientific computing.

Python List: More versatile for general-purpose programming but lacks built-in support for advanced mathematical operations.

# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [2]:
import numpy as np 
array =np.array( [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]] )

shape = array.shape
size = array.size
ndim = array.ndim
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", ndim)

Shape: (3, 4)
Size: 12
Dimensions: 2


# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [8]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

row = arr[0]
print("First row =",row)

First row = [1 2 3 4]


# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [20]:
array = np.array ([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
# to access the third row and forth column ele
ele = array[2,3]
ele

12

# 6. Write coed to extract all odd -indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [32]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
# to extract all the odd index we can jump
odd_ind = array[1::2, 1::2]
print(f"the odd indexed element is {odd_ind}")

the odd indexed element is [[6 8]]


#  7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [50]:
random_array = np.random.rand(3,3)
# to print between 0 to 1  
print(random_array)

[[0.70716721 0.52214112 0.78263884]
 [0.69042674 0.95853495 0.03365645]
 [0.0057598  0.23248511 0.18278573]]


# 8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand: This function generates random numbers from a uniform distribution between 0 and 1. It takes the shape of the output array as arguments and returns an array with random values.

np.random.randn: This function generates random numbers from a standard normal distribution (mean 0, standard deviation 1). Like rand, it also takes the shape of the output array as arguments, but it returns an array with random values sampled from a normal distribution.

In [52]:
random_array_rand = np.random.rand(3,3)
random_array_randn = np.random.randn(3,3)

In [56]:
print("If we take random.randn")
random_array_randn 

If we take random.randn


array([[-0.35494421, -1.43881758,  0.56503546],
       [ 0.2558417 ,  0.83473601,  0.28083479],
       [ 1.03605173,  1.22030253, -0.82419794]])

In [64]:
random_array_rand = np.random.rand(3,3)
print("If we take random.rand")

If we take random.rand


# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [63]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

increse_dim = np.expand_dims(array, axis =1)

print("The dimension of previous array",array.ndim)
print("The dimension of new array",increse_dim.ndim)


The dimension of previous array 2
The dimension of new array 3


# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

In [76]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#to transpose a matrix we can use a function transpose  
transpose_array = array.transpose()
print(f"the array before transpose :\n {array}")
print(f"the array after transpose :\n {transpose_array}")

the array before transpose :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
the array after transpose :
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1 Index wise multiplication
# 2 Matix multiplication
# 3 Add both the matics
# 4 Subtact matix B from A 
# 5 Divide Matix B by A

In [98]:

A1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

# 1 Index wise multiplication
multi = A1*B2
print("The index wise multiplication result is: \n",multi)

#2 Matrix multiplication 
mat_multi = A1 @ B2.T  # Transpose B2 to match dimensions for multiplication
print("The result of Matrix multiplication is :\n",mat_multi)


#3 Adding the array 
add = A1 + B2
print("The resutlt of addition is \n",add)

# 4 subtracting an array 
sub =  B2 -A1 
print("The result of subtraction is: \n",sub)

#5 divide Matrix B2 by A1
divide = B2/A1
print("The result of division B2 by A1 is :\n",divide)


The index wise multiplication result is: 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
The result of Matrix multiplication is :
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
The resutlt of addition is 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
The result of subtraction is: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The result of division B2 by A1 is :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 12. Which function in Numpy can be used to swap the byte order of an array?

In [101]:
# byteswap() is used to swap the byte order of an array
arr = np.array([1, 2, 3, 4])

# Swap the byte order of the array
arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Array with byte order swapped:\n", arr_swapped)


Original array: [1 2 3 4]
Array with byte order swapped:
 [ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]


# 13. What is the significance of the np.linalg.inv function?


The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

The significance of this function lies in various mathematical and computational applications, particularly in linear algebra and solving systems of linear equations.

# 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape, as long as the total number of elements remains the same.
for example 2*3 matrix can be reshaped in  3*2 matix or 6*1 or 1*6

In [108]:
#
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Reshape the array to a new shape
reshaped_array = np.reshape(array,(3,2))
reshaped_array

array([[1, 2],
       [3, 4],
       [5, 6]])

# 15. What is broadcasting in Numpy?

Broadcasting allows arrays of different shapes to be combined together in arithmetic and logical operations. It enables you to perform element-wise operations between arrays with different shapes, without the need to explicitly reshape or replicate the arrays to match each other's shapes.

In [109]:
# two arrays of different shapes
x = np.array([1, 2, 3])     # Shape: (3,)
y = np.array([[4], [5], [6]])  # Shape: (3, 1)

# Perform element-wise addition using broadcasting
result = x + y

print("Result of broadcasting:")
print(result)


Result of broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]
